device: cpu  # cuda
BATCH_SIZE: 8
NUM_EPOCHS: 3
NUM_WORKERS: 4
PIN_MEMORY: True
LOAD_MODEL: False
DATA_DIR: cell
save_checkpoint: True
use_upsample: False
features:
  - 64
  - 128 # 128
  - 256 # 256
#  - 512
up:
  stride: 1
  kernel_size: 3
down:
  stride: 1
  kernel_size: 3
pooling:
  kernel_size: 2
  stride: 2
bottleneck:
  kernel_size: 3
  stride: 1
optimizer:
  name: SGD # SGD
  learning_rate: 1e-2
  opts:
    SGD:
      momentum: 0.9  # for SGD
      weight_decay: 1e-3  # for SGD